import { index, type RouteConfig, route } from "@react-router/dev/routes";

export default [
  route(
    ".well-known/apple-app-site-association",
    "routes/well-known.apple-app-site-association.tsx",
  ),
  route(".well-known/assetlinks.json", "routes/well-known.assetlinks.json.tsx"),
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("account", "routes/account.tsx"),
  route("account/blocked-users", "routes/account.blocked-users.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("confirm-delete-account", "routes/confirm-delete-account.tsx"),
  route("applications", "routes/applications.tsx"),
  route("communities", "routes/communities._index.tsx"),
  route("communities/create", "routes/communities.create.tsx"),
  route("communities/mine", "routes/communities.mine.tsx"),
  route(
    "communities/:slug/applications/:applicationId",
    "routes/communities.$slug.applications.$applicationId.tsx",
  ),
  route(
    "communities/:slug/applications",
    "routes/communities.$slug.applications.tsx",
  ),
  route("communities/:slug/apply", "routes/communities.$slug.apply.tsx"),
  route("communities/:slug/settings", "routes/communities.$slug.settings.tsx"),
  route("communities/:slug/members", "routes/communities.$slug.members.tsx"),
  route("communities/:slug/links", "routes/communities.$slug.links.tsx"),
  route(
    "communities/:slug/analytics",
    "routes/communities.$slug.analytics.tsx",
  ),
  route("communities/:slug/bots", "routes/communities.$slug.bots.tsx"),
  route("communities/:slug/boards", "routes/communities.$slug.boards.tsx"),
  route("communities/:slug", "routes/communities.$slug.tsx"),
  route("boards", "routes/boards.tsx"),
  route("boards/:boardSlug/create", "routes/boards.$boardSlug.create.tsx"),
  route(
    "boards/:boardSlug/posts/:postId/edit",
    "routes/boards.$boardSlug.posts.$postId.edit.tsx",
  ),
  route(
    "boards/:boardSlug/posts/:postId",
    "routes/boards.$boardSlug.posts.$postId.tsx",
  ),
  route("boards/:boardSlug", "routes/boards.$boardSlug.tsx"),
  route("admin/boards", "routes/admin.boards.tsx"),
  route("admin/masquerade", "routes/admin.masquerade.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("policy", "routes/policy.tsx"),
] satisfies RouteConfig;
